### ISSUE TITLE
Completar BDD en Mongo (hacer relacion 1:N y N:1 entre tablas)

### ISSUE THREAD

**Issue by Diekrul** [dpalmasan/dev-job-analytics#9]

**Comment by dpalmasan** [comment]
Pregunta, sobre este issue. Como MongoDB es no relacional, quizás se complica un poco en el diseño? Pregunto como es NoSQL y no soporta joins, quizás el diseño debería ser otro? Capaz tenemos que investigar

**Comment by dpalmasan** [comment]
Esto ya fue discutido, hicimos la DB en MongoDB y ya hay una primera implementación.
